remote_theme: reinhart1010/HAM
title: "Shift's Digital Garden"
ham:
  site_icon: "/shift-fullman-lg Background Removed.png"
  site_favicon: null # Your site favicon, in case you have a spare favicon.ico for it
  contributing: # Additional metadata for "Contribute to This Page" section on sidebar
    discuss: # For "Discuss" (or "Talk page" on MediaWiki)
      type: url # Currently supports "url". Support for other discussion widgets such as DiscussBot (Telegram), Disqus, and Utteranc.es are coming soon.
      url: https://github.com/reinhart1010/shift/discussions/
    view_source_base_url: https://github.com/reinhart1010/shift/blob/main/ # The base URL to publicly view the original (Markdown) source code
    issue_url: https://github.com/reinhart1010/shift/issues/ # The URL to report an issue related to site or content
